### ISSUE TITLE
Scrolling bug when use ListView at body.

### ISSUE THREAD

**Issue by jja08111** [shiburagi/Coordinator-Layout#1]
Hi, I face the bug when I use `ListView.builder` at `body` in `CoordinatorLayout`. 

When I quickly tap the screen many times, it causes a bug and the screen freezes.

I also use `physics: NeverScrollableScrollPhysics()`, `primary: false` at the same time, but this one can't scroll the list.

```dart 
CoordinatorLayout(
        headerMaxHeight: 200,
        headerMinHeight: kToolbarHeight + MediaQuery.of(context).padding.top,
        headers: [
          Builder(builder: (context) {
            return SliverOverlapAbsorber(
              handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
              sliver: SliverSafeArea(
                top: false,
                sliver: SliverCollapsingHeader(
                  builder: (context, offset, diff) {
                    return Container(
                      color: Colors.redAccent,
                    );
                  },
                ),
              ),
            );
          }),
        ],
        body: ListView.builder(
          itemCount: 10,
          itemBuilder: (context, index) {
            return Text('List $index');
          },
        )
    );

```

```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 583 pos 12: '_hold == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragStart (package:flutter/src/widgets/scrollable.dart:583:12)
#3      DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:412:53)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#5      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:412:7)
#6      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:336:7)
...
Handler: "onStart"
Recognizer: VerticalDragGestureRecognizer#af8ad
  start behavior: start
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 572 pos 12: '_hold == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:572:12)
#3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:401:51)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:401:7)
#6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:264:7)
...
Handler: "onDown"
Recognizer: VerticalDragGestureRecognizer#af8ad
  start behavior: start
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 583 pos 12: '_hold == null': is not true.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by shiburagi** [comment]
Hi, can u try set ```physics: NeverScrollableScrollPhysics()`` on ListView,

```dart
ListView.builder(
          physics: NeverScrollableScrollPhysics(),
         ...
)

``

**Comment by jja08111** [comment]
Thanks for your reply!

I also try `physics: NeverScrollableScrollPhysics()`, but It still doesn't work with same error.

I think `scrollController.animateTo()` make this bug.

**Comment by jja08111** [comment]
I solved it by adding some value in `coordinator.dart` using [#14452](https://github.com/flutter/flutter/issues/14452#issuecomment-716191048)

```dart

Future<void> scrollAnimateToRunning;

...

Future.delayed(Duration.zero, () async {
          if(scrollAnimateToRunning != null) {
            await scrollAnimateToRunning;
          }

          scrollAnimateToRunning = scrollController.animateTo(
            snapOffset,
            curve: Curves.ease,
            duration: const Duration(milliseconds: 100),
          );
        });
```
